### ISSUE TITLE
How to make aspect ratio not be changed?

### ISSUE THREAD

**Issue by yorkwang** [kishikawakatsumi/PEPhotoCropEditor#5]
After setting  constrain, aspect ratio still could be changed when dragging the crop rect.

**Comment by kishikawakatsumi** [comment]
It is not implemented yet.
Thank you for your suggestion.
I will do my best to implement this feature as soon as possible.

**Comment by yorkwang** [comment]
Great! Thanks for your quick reply!

**Comment by kishikawakatsumi** [comment]
Done. 91067dc36fbfc56a3ccacb5ba9e113f2b8867230
Use `keepingCropAspectRatio` property set to `YES`.

**Comment by Abderezai** [comment]
I still see my aspect ratio not kept the same if I drag the crop area to the bounds of an image.
For example, I have aspect ratio of 1, which results in a square area inside my rectangle image. but then when I take the crop area and try to expand it the corner, the crop area expands into the rectangle, violating the 1 ratio.

Thanks
